### ISSUE TITLE
VBET tool for riparian zones in Western Australia - User Inquiry

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RCAT#4]
A User submitted this inquiry:

> VBET tool for riparian zones in Western Australia
Hi Joe,

 

I am trying to use the VBET tool (using ArcMap 10.6) to derive a riparian zone for the Avon River Basin in Western Australia. I have a 10m DEM and hydrographic stream network but have been unable to get the tool to run. It stalls about 2-3 hours in to the analysis while “Calculating Drainage Area”; the error I get is variations on the one below:

 

 

```
Traceback (most recent call last):

  File "<string>", line 193, in execute

  File "G:\WNRMShared\G4 Corporate Governance\GO4063_NRM Strategy and Dashboard\TPC\Sedimentation\Riparian Zone\VBET_0.2.1\VBET_0.2.1\VBET.py", line 62, in main

    calc_drain_area(DEM)

  File "G:\WNRMShared\G4 Corporate Governance\GO4063_NRM Strategy and Dashboard\TPC\Sedimentation\Riparian Zone\VBET_0.2.1\VBET_0.2.1\VBET.py", line 201, in calc_drain_area

    DrainArea.save(DrArea_path)

RuntimeError: ERROR 999998: Unexpected Error.

 

Failed to execute (VBETtool).

Failed at Fri Mar  9 17:37:00 2018 (Elapsed Time: 3 hours 3 minutes 50 seconds)
```
 

Can you provide any assistance? I have Googled the stuffing out of it and have come to the conclusion that something in the script doesn’t agree with the fields in my stream network. So I tried to run the NHD Network Builder but that didn’t run successfully either. I am very excited by this tool and would love to get it to run.

 

 

Regards,

**Comment by joewheaton** [comment]
Glad to hear you're having a play with VBET down under.  @jtgilbert  and @wally-mac or @bangen may have better or further ideas then below. 

By far, the longest geoprocessing operation in VBET is the drainage area calculation. 2-3 hours for a large area is totally plausible. From what you described, it sounds to me like its actually doing the drainage area calculation fine (for 2-3 hours of chugging away) and then it crashes when writing that to disc? However, here's what comes to mind from what you've provided as possibilities:
- There is a strong possibility given this is using ArcPy code that the space in your path `"G:\WNRMShared\G4 Corporate Governance\GO4063_NRM Strategy and Dashboard\TPC\Sedimentation\Riparian Zone\VBET_0.2.1\VBET_0.2.1\VBET.py"` is causing the write to disc operation to crash. I would try running the tool not from that horrible burried path on a network drive, but from a local drive (e.g. `c:\VBET\MyProject`) and see if it works. If it does you can always move it over to that network path.
- If this is still crashing in the tool, you can always run a [flow accumulation](https://desktop.arcgis.com/en/arcmap/latest/tools/spatial-analyst-toolbox/how-flow-accumulation-works.htm) drainage area calculation separately and then load this as an input to the tool in the optional **Drainage Area Calculation Raster** (make sure units are square kilometers).  
- I am not 100% sure that the tool works or has been tested in 10.6 (sometimes there are Python dependencies that are version specific (annoyingly)

Let us know if it works.

**Comment by joewheaton** [comment]
Never heard back from user...
